#!/bin/bash
#26.06.2021 18:33:38 Generated by lincentrator
filhere="drive-harddisk.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/drive-harddisk.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/drive-harddisk.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было 8e692c6c16c41898aa98191b42848a8f
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/drive-harddisk.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done

#26.06.2021 18:34:25 Added by lincentrator
filhere="drive-optical.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/drive-optical.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/drive-optical.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было 12a289fed033e9184f30bb6534865e92
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/drive-optical.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done

#26.06.2021 18:34:44 Added by lincentrator
filhere="computer.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/computer.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/computer.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было 0037033c0c19fc98fcd926e6d26ab1a2
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/computer.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done

#26.06.2021 18:35:01 Added by lincentrator
filhere="drive-removable-media.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/drive-removable-media.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/drive-removable-media.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было 0a96d6700a010f87fa7fdd9eb0749fd0
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/drive-removable-media.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done

#26.06.2021 18:35:18 Added by lincentrator
filhere="video-display.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/video-display.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/video-display.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было 36a790d237da3bd2fe09180b5b6a714e
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/video-display.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done

#26.06.2021 18:35:44 Added by lincentrator
filhere="printer.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/printer.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/printer.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было bea37de0a0deb832868dce6b3dd98944
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/printer.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done

#26.06.2021 18:38:32 Added by lincentrator
filhere="processor.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/processor.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/processor.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было 9ee68c21b5af3e97b3c8d581725083d8
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/processor.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done

#26.06.2021 18:38:36 Added by lincentrator
filhere="scanner.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/scanner.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/scanner.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было 00544d7f01b26320c630456890f398e9
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/scanner.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done

#26.06.2021 18:40:34 Added by lincentrator
filhere="input-mouse.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/input-mouse.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/input-mouse.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было c3ba6008411276a3fda942fc1f375677
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/input-mouse.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done

#26.06.2021 18:40:42 Added by lincentrator
filhere="input-keyboard.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/input-keyboard.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/input-keyboard.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было a2c064c5c06d017fc76b2c78a8c4691e
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/input-keyboard.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done

#26.06.2021 18:41:06 Added by lincentrator
filhere="input-gaming.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/input-gaming.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/32/input-gaming.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было a1546f2096c94916ad08fdcd55690a9f
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/input-gaming.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done
