#!/bin/bash
#20.08.2021 23:59:04 Generated by lincentrator
filhere="../../../../../../icons/SE98/places/24/network-workgroup.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/icons/SE98/places/24/network-workgroup.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/places/24/network-workgroup.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было dc879a37ac940827ae868f3e5e6317af
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/../../../../../../icons/SE98/places/24/network-workgroup.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done

#21.08.2021 00:09:45 Added by lincentrator
filhere="../../../../../../icons/SE98/places/24/user-bookmarks.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/icons/SE98/places/24/user-bookmarks.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/places/24/user-bookmarks.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было 0476721fdbe45803cc11c9c6e5935977
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/../../../../../../icons/SE98/places/24/user-bookmarks.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done
