#!/bin/bash
#26.06.2021 18:29:05 Generated by lincentrator
filhere="drive-optical.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/22/drive-optical.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/22/drive-optical.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было 5fc569a4e864946edd74347d8e098dd1
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/drive-optical.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done
