#!/bin/bash
#26.06.2021 18:26:38 Generated by lincentrator
filhere="drive-optical.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/64/drive-optical.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/GitHub/Win98SE/Icons/SE98/devices/64/drive-optical.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было aa2f436069fb188d1f270d2cd2a64f57
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/drive-optical.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done
