#!/bin/bash
#15.06.2021 00:01:27 Generated by lincentrator
filhere="folder-open.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/icons/SE98/places/16/folder-open.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/icons/SE98/places/16/folder-open.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было 71d5e9460a41b6a660ca4efbc1406c06
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/folder-open.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done

#15.06.2021 00:04:35 Added by lincentrator
filhere="start-here.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/icons/SE98/places/16/start-here.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/icons/SE98/places/16/start-here.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было ef3a60054592b4e8751fedfa418cd29f
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/start-here.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done

#15.06.2021 00:07:50 Added by lincentrator
filhere="folder-remote.png"
fil="$(realpath -s "$filhere")" #было /home/joker/Документы/icons/SE98/places/16/folder-remote.png
filr="$(realpath "$filhere")" #было /home/joker/Документы/icons/SE98/places/16/user-share.png
cmd="md5sum"
if [ -h "$fil" ];then
 unlink "$filhere"
 cp -f "$filr" "$filhere"
fi
filsum=$($cmd "$filr"|sed 's/ .*//g') #было 7ea9f97d25e2f092e99b429e6245dfb1
$cmd ./* 2>/dev/null|grep $filsum|grep -Gv "/folder-remote.png"$|sed -e 's/^[^ ]* *//g'|while read line; do
ln -srf "$filhere" "$line"
done
